name: ctest
on: push
env:
  NO_BENCHMARKS: 1
  NO_DOCS: 1

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: threeal/cmake-action@v1.3.0
      with:
        run-build: false
    - uses: threeal/ctest-action@v1.1.0
      with:
        args: "-j"
